version: '3.4'

services:
  mars.web:
    image: ${DOCKER_REGISTRY-}marsweb
    build:
      context: .
      dockerfile: Mars.Web/Dockerfile
    environment:
      - SeqServer=http://seq
    networks:
      - jaegernet

  mars.extraapi:
    image: ${DOCKER_REGISTRY-}marsextraapi
    build:
        context: .
        dockerfile: Mars.ExtraApi/Dockerfile
    environment:
        - SeqServer=http://seq
    networks:
        - jaegernet

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "8888:80"
    volumes:
      - /datadrive:/data
    environment:
      - ACCEPT_EULA=Y

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - jaegernet
    depends_on:
      - mars.web

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

networks:
  jaegernet:

volumes:
  prom_data:  